# Generated by Django 5.2.4 on 2025-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('O', 'Open'), ('I', 'In progress'), ('C', 'Closed')], default='D', max_length=1)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['-created_at'], name='tickets_tic_created_c2132d_idx')],
            },
        ),
    ]
